apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    # to get at port 3000 inside the container, you need to get at port 3000 in the service
    - port: 3000
      targetPort: 3000
