apiVersion: apps/v1
# The knd of object
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  # The component that we will be managing will be web
  selector:
    matchLabels:
      component: web
  # Pod template
  template:
    metadata:
      # The selector and pod labels are how the deployment is going to identify which pods it needs to manage
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: npwhite/multi-client
          ports:
            # this is the port that will be mapped to the multi client image
            - containerPort: 3000
